const express = require('express')
const router = express.Router()
const multer = require('multer')
const authMiddleware = require('../middleware/auth.middleware')
const Session = require('../models/Session')
const Group = require('../models/Group')

const storage = multer.memoryStorage()
const upload = multer({ storage, limits: { fileSize: 10 * 1024 * 1024 } })

// CREATE SESSION
router.post('/create', authMiddleware, upload.single('document'), async (req, res) => {
  try {
    const { groupId, topic } = req.body
    const group = await Group.findById(groupId).populate('members', 'name email')
    if (!group) return res.status(404).json({ message: 'Group not found' })

    // Extract document text (placeholder for now - AI will do this later)
    let documentText = ''
    let documentName = ''
    if (req.file) {
      documentName = req.file.originalname
      documentText = 'DOCUMENT_UPLOADED:' + req.file.originalname
    }

    // Divide members into subgroups of max 3
    const members = group.members
    const subGroups = []
    const subGroupSize = 3
    for (let i = 0; i < members.length; i += subGroupSize) {
      const chunk = members.slice(i, i + subGroupSize)
      subGroups.push({
        name: `Group ${subGroups.length + 1}`,
        members: chunk.map(m => m._id),
        leaderId: chunk[0]._id,
        topics: [],
        isDone: false
      })
    }

    // Placeholder topics (AI will extract these from document later)
    const placeholderTopics = [
      `${topic} - Core Concepts`,
      `${topic} - Key Principles`,
      `${topic} - Practical Applications`,
      `${topic} - Common Problems`,
      `${topic} - Advanced Topics`,
      `${topic} - Summary Points`
    ]

    // Distribute topics across subgroups evenly
    const topicsPerGroup = Math.ceil(placeholderTopics.length / subGroups.length)
    subGroups.forEach((sg, i) => {
      sg.topics = placeholderTopics.slice(i * topicsPerGroup, (i + 1) * topicsPerGroup)
    })

    // Placeholder flashcards (AI will generate these later)
    const placeholderFlashcards = [
      { question: `What is the main concept of ${topic}?`, answer: 'Answer will be generated by AI from your document.' },
      { question: `Give a real-world example of ${topic}.`, answer: 'Answer will be generated by AI from your document.' },
      { question: `What are the key principles of ${topic}?`, answer: 'Answer will be generated by AI from your document.' },
      { question: `How is ${topic} applied in practice?`, answer: 'Answer will be generated by AI from your document.' },
      { question: `What are common mistakes when studying ${topic}?`, answer: 'Answer will be generated by AI from your document.' }
    ]

    const session = new Session({
      group: groupId,
      createdBy: req.user.id,
      topic,
      documentText,
      documentName,
      topics: placeholderTopics,
      subGroups,
      flashcards: placeholderFlashcards,
      currentPhase: 0,
      status: 'waiting'
    })

    await session.save()
    res.json(session)
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})

// GET SESSION BY ID
router.get('/:sessionId', authMiddleware, async (req, res) => {
  try {
    const session = await Session.findById(req.params.sessionId)
      .populate('group')
      .populate('createdBy', 'name email')
      .populate('subGroups.members', 'name email')
      .populate('subGroups.leaderId', 'name email')
    if (!session) return res.status(404).json({ message: 'Session not found' })
    res.json(session)
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})

// GET ACTIVE SESSION FOR A GROUP
router.get('/group/:groupId/active', authMiddleware, async (req, res) => {
  try {
    const session = await Session.findOne({
      group: req.params.groupId,
      status: { $in: ['waiting', 'active'] }
    })
      .populate('subGroups.members', 'name email')
      .populate('subGroups.leaderId', 'name email')
    res.json(session)
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})

// END SESSION
router.post('/:sessionId/end', authMiddleware, async (req, res) => {
  try {
    const session = await Session.findById(req.params.sessionId)
    if (!session) return res.status(404).json({ message: 'Session not found' })
    if (session.createdBy.toString() !== req.user.id) {
      return res.status(403).json({ message: 'Only the session creator can end the session' })
    }
    session.status = 'ended'
    await session.save()
    res.json({ message: 'Session ended' })
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})

// MARK SUBGROUP AS DONE
router.post('/:sessionId/subgroup/:subGroupIndex/done', authMiddleware, async (req, res) => {
  try {
    const session = await Session.findById(req.params.sessionId)
    if (!session) return res.status(404).json({ message: 'Session not found' })
    session.subGroups[req.params.subGroupIndex].isDone = true
    await session.save()
    const allDone = session.subGroups.every(sg => sg.isDone)
    res.json({ message: 'Subgroup marked done', allDone })
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})

module.exports = router