const express = require('express')
const router = express.Router()
const multer = require('multer')
const authMiddleware = require('../middleware/auth.middleware')
const Session = require('../models/Session')
const Group = require('../models/Group')

const storage = multer.memoryStorage()
const upload = multer({ storage, limits: { fileSize: 10 * 1024 * 1024 } })

// CREATE SESSION
router.post('/create', authMiddleware, upload.array('documents', 10), async (req, res) => {
  try {
    const { groupId, topic } = req.body

    const group = await Group.findById(groupId).populate('members', 'name email')
    if (!group) return res.status(404).json({ message: 'Group not found' })

    // ── Member limit ────────────────────────────────────────────────
    if (group.members.length > 21)
      return res.status(400).json({ message: 'Session cannot exceed 21 members. Please split into smaller groups.' })

    // ── Parse uploaded PDFs ─────────────────────────────────────────
    const documents = []
    if (req.files && req.files.length > 0) {
      for (const file of req.files) {
        try {
          let text = ''
          if (file.mimetype === 'application/pdf' || file.originalname.endsWith('.pdf')) {
            const pdfParse = require('pdf-parse')
            const parsed = await pdfParse(file.buffer)
            text = parsed.text
          } else if (
            file.mimetype === 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' ||
            file.originalname.endsWith('.docx')
          ) {
            const mammoth = require('mammoth')
            const result = await mammoth.extractRawText({ buffer: file.buffer })
            text = result.value
          }
          documents.push({ name: file.originalname, text })
        } catch (e) {
          documents.push({ name: file.originalname, text: '' })
        }
      }
    }

    // ── Build subgroups ─────────────────────────────────────────────
    const members = group.members
    const subGroups = []
    const subGroupSize = 3
    for (let i = 0; i < members.length; i += subGroupSize) {
      const chunk = members.slice(i, i + subGroupSize)
      subGroups.push({
        name: `Group ${subGroups.length + 1}`,
        members: chunk.map(m => m._id),
        leaderId: chunk[0]._id,
        topics: [],
        isDone: false
      })
    }

    const placeholderTopics = [
      `${topic} - Core Concepts`,
      `${topic} - Key Principles`,
      `${topic} - Practical Applications`,
      `${topic} - Common Problems`,
      `${topic} - Advanced Topics`,
      `${topic} - Summary Points`
    ]

    const topicsPerGroup = Math.ceil(placeholderTopics.length / subGroups.length)
    subGroups.forEach((sg, i) => {
      sg.topics = placeholderTopics.slice(i * topicsPerGroup, (i + 1) * topicsPerGroup)
    })

    const placeholderFlashcards = [
      { question: `What is the main concept of ${topic}?`, answer: 'Answer will be generated by AI from your document.' },
      { question: `Give a real-world example of ${topic}.`, answer: 'Answer will be generated by AI from your document.' },
      { question: `What are the key principles of ${topic}?`, answer: 'Answer will be generated by AI from your document.' },
      { question: `How is ${topic} applied in practice?`, answer: 'Answer will be generated by AI from your document.' },
      { question: `What are common mistakes when studying ${topic}?`, answer: 'Answer will be generated by AI from your document.' }
    ]

    const session = new Session({
      group: groupId,
      createdBy: req.user.id,
      topic,
      documents,
      topics: placeholderTopics,
      subGroups,
      flashcards: placeholderFlashcards,
      currentPhase: 0,
      status: 'waiting',
      phaseStartedAt: new Date()
    })

    await session.save()
    res.json(session)
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})

// ⚠️ MUST BE BEFORE /:sessionId
// GET ACTIVE SESSION FOR A GROUP
router.get('/group/:groupId/active', authMiddleware, async (req, res) => {
  try {
    const session = await Session.findOne({
      group: req.params.groupId,
      status: { $in: ['waiting', 'active'] }
    })
      .populate('subGroups.members', 'name email')
      .populate('subGroups.leaderId', 'name email')
    res.json(session)
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})

// GET SESSION BY ID
router.get('/:sessionId', authMiddleware, async (req, res) => {
  try {
    const session = await Session.findById(req.params.sessionId)
      .populate('group')
      .populate('createdBy', 'name email')
      .populate('subGroups.members', 'name email')
      .populate('subGroups.leaderId', 'name email')
    if (!session) return res.status(404).json({ message: 'Session not found' })

    const phaseDurations = [10, 20, 10, 15, 0]
    const phaseDuration = phaseDurations[session.currentPhase] * 60
    let timeRemaining = null
    if (session.phaseStartedAt && phaseDuration > 0) {
      const elapsed = Math.floor((Date.now() - new Date(session.phaseStartedAt).getTime()) / 1000)
      timeRemaining = Math.max(0, phaseDuration - elapsed)
    }

    res.json({ ...session.toObject(), timeRemaining })
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})

// ADVANCE PHASE
router.post('/:sessionId/phase', authMiddleware, async (req, res) => {
  try {
    const session = await Session.findById(req.params.sessionId)
    if (!session) return res.status(404).json({ message: 'Session not found' })
    if (session.createdBy.toString() !== req.user.id) {
      return res.status(403).json({ message: 'Only the session creator can advance the phase' })
    }
    session.currentPhase = req.body.phase
    session.status = 'active'
    session.phaseStartedAt = new Date()
    await session.save()
    const populated = await Session.findById(session._id)
      .populate('group')
      .populate('createdBy', 'name email')
      .populate('subGroups.members', 'name email')
      .populate('subGroups.leaderId', 'name email')
    res.json(populated)
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})

// END SESSION
router.post('/:sessionId/end', authMiddleware, async (req, res) => {
  try {
    const session = await Session.findById(req.params.sessionId)
    if (!session) return res.status(404).json({ message: 'Session not found' })
    if (session.createdBy.toString() !== req.user.id) {
      return res.status(403).json({ message: 'Only the session creator can end the session' })
    }
    session.status = 'ended'
    await session.save()
    res.json({ message: 'Session ended' })
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})

// DELETE SESSION
router.delete('/:sessionId', authMiddleware, async (req, res) => {
  try {
    const session = await Session.findById(req.params.sessionId)
    if (!session) return res.status(404).json({ message: 'Session not found' })
    if (session.createdBy.toString() !== req.user.id) {
      return res.status(403).json({ message: 'Only the session creator can delete this session' })
    }
    await Session.findByIdAndDelete(req.params.sessionId)
    res.json({ message: 'Session deleted' })
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})

// MARK SUBGROUP AS DONE
router.post('/:sessionId/subgroup/:subGroupIndex/done', authMiddleware, async (req, res) => {
  try {
    const session = await Session.findById(req.params.sessionId)
    if (!session) return res.status(404).json({ message: 'Session not found' })
    session.subGroups[req.params.subGroupIndex].isDone = true
    await session.save()
    const allDone = session.subGroups.every(sg => sg.isDone)
    res.json({ message: 'Subgroup marked done', allDone })
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})

// SAVE STUDENT SCORE
router.post('/:sessionId/score', authMiddleware, async (req, res) => {
  try {
    const { score, wrongCount, totalCount } = req.body
    const session = await Session.findById(req.params.sessionId)
    if (!session) return res.status(404).json({ message: 'Session not found' })
    session.scores = session.scores.filter(s => s.userId.toString() !== req.user.id)
    session.scores.push({
      userId: req.user.id,
      userName: req.user.name,
      score,
      wrongCount,
      totalCount
    })
    await session.save()
    res.json({ message: 'Score saved' })
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})

// GET PAST SESSIONS FOR A GROUP
router.get('/group/:groupId/history', authMiddleware, async (req, res) => {
  try {
    const sessions = await Session.find({
      group: req.params.groupId,
      status: 'ended'
    })
      .populate('createdBy', 'name email')
      .sort({ updatedAt: -1 })
    res.json(sessions)
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})


// KICK MEMBER
router.post('/:sessionId/kick', authMiddleware, async (req, res) => {
  try {
    const session = await Session.findById(req.params.sessionId)
    if (!session) return res.status(404).json({ message: 'Session not found' })
    if (session.createdBy.toString() !== req.user.id)
      return res.status(403).json({ message: 'Only the session creator can kick members' })
    res.json({ message: 'Kick signal sent' })
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})

// LIVEKIT TOKEN
router.get('/:sessionId/livekit-token', authMiddleware, async (req, res) => {
  try {
    const { AccessToken } = require('livekit-server-sdk')
    const session = await Session.findById(req.params.sessionId)
    if (!session) return res.status(404).json({ message: 'Session not found' })

    const token = new AccessToken(
      process.env.LIVEKIT_API_KEY,
      process.env.LIVEKIT_API_SECRET,
      { identity: req.user.name || req.user.id }
    )
    token.addGrant({
      roomJoin: true,
      room: req.params.sessionId,
      canPublish: true,
      canSubscribe: true,
      canPublishScreen: true
    })

    res.json({ token: await token.toJwt(), url: process.env.LIVEKIT_URL })
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})
module.exports = router